env:
  browser: true
  es2020: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/react
  - plugin:import/warnings
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - import
settings:
  import/ignore:
    - \.coffee$
    - \.(scss|less|css)$
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
rules:
  max-len:
    - warn
  indent:
    - error
    - 4
    - SwitchCase: 1
  react/prefer-stateless-function:
    - off
  react/jsx-indent:
    - error
    - 4
  react/jsx-indent-props:
    - error
    - 4
  react/forbid-prop-types:
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
  eqeqeq:
    - error
    - smart
  no-unsafe-negation:
    - error
  operator-assignment:
    - error
    - always
  no-plusplus:
    - off
  brace-style:
    - error
    - 1tbs
  curly:
    - error
    - all
  comma-dangle:
    - error
    - always-multiline
  jsx-quotes:
    - error
    - prefer-double
  object-shorthand:
    - error
    - always
  camelcase:
    - error
    - properties: always
  no-inner-declarations:
    - error
    - functions
  use-isnan:
    - error
  block-spacing:
    - error
    - always
  no-this-before-super:
    - error
  no-cond-assign:
    - error
    - always
  no-return-assign:
    - error
    - except-parens
  no-dupe-keys:
    - error
  no-extra-semi:
    - error
  no-func-assign:
    - error
  no-loop-func:
    - error
  no-multi-str:
    - error
  no-redeclare:
    - error
  no-sparse-arrays:
    - error
  no-fallthrough:
    - error
  no-duplicate-case:
    - error
  no-undef:
    - error
  no-unreachable:
    - warn
  no-undefined:
    - error
  no-ex-assign:
    - error
  no-constant-condition:
    - warn
  no-dupe-args:
    - error
  no-dupe-class-members:
    - error
  no-eval:
    - warn
  no-extra-boolean-cast:
    - error
  require-yield:
    - error
  valid-typeof:
    - error
  no-irregular-whitespace:
    - error
    - skipComments: true
  no-mixed-spaces-and-tabs:
    - error
  no-class-assign:
    - error
  no-const-assign:
    - error
  no-negated-in-lhs:
    - error
  block-scoped-var:
    - error
  no-use-before-define:
    - error
  wrap-iife:
    - error
    - inside
  new-cap:
    - warn
    - properties: false
  arrow-parens:
    - error
    - always
  arrow-spacing:
    - error
  constructor-super:
    - error
  react/jsx-uses-vars:
    - error
  react/jsx-uses-react:
    - error
  no-unused-vars:
    - warn
  object-curly-spacing:
    - error
    - always
  import/no-unresolved:
    - error
    - commonjs: true
      amd: true
      caseSensitive: true
  import/named:
    - error
  import/namespace:
    - error
  import/default:
    - error
  import/export:
    - error
  no-template-curly-in-string:
    - warn
  no-multiple-empty-lines:
    - off

